version: "3.7"

services:
  redis:
    image: redis
    restart: on-failure
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - backend
    volumes:
      - datadir-redis:/data
    ports:
      - 6379:6379
networks:
  backend:
    driver: bridge

volumes:
  datadir-redis: